version: '3.5'

services:
    app:
        container_name: sample-laravel
        image: sample-laravel
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html/DockerTest


